#ifndef _DEFINES_H_
#define _DEFINES_H_

#define START_BYTE 254
#define HEARTBEAT_TIMEOUT 500
#define HUMID_TIMEOUT 500
#define LIGHTTOWER_TIMEOUT 250
#define OCS_TIMEOUT 500

#define LIGHTTOWER_RED	13
#define LIGHTTOWER_YELLOW 11
#define LIGHTTOWER_GREEN 12

#define KILL_BATT A4
#define KILL_STATUS A3

#define MANUAL_OPERATION 0x01

#define XBEE_BAUDRATE 115200

#endif