#ifndef _DEFINES_H_
#define _DEFINES_H_

#define HEARTBEAT_TIMEOUT 500
#define HUMID_TIMEOUT 500
#define BATT_TIMEOUT 250
#define WINDSPEED_TIMEOUT 100
#define LIGHTTOWER_TIMEOUT 250
#define OCS_TIMEOUT 3000
#define AUTONOMOUS_MODE_TIMEOUT 300

#define LIGHTTOWER_RED	13
#define LIGHTTOWER_YELLOW 11
#define LIGHTTOWER_GREEN 12

#define AUTONOMOUS 0
#define MANUAL_OCS 1
#define MANUAL_RC 2
#define STATION_KEEP 3

#define XBEE_BAUDRATE 115200

#endif